name: CI/CD Deployment

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Vérifier le dépôt
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Installer Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'

      # 3. Installer les dépendances
      - name: Install dependencies
        run: |
          cd Back
          npm install

      # 4. Mettre le NODE_ENV en production
      - name: Set NODE_ENV to prod
        run: echo "NODE_ENV=prod" >> $GITHUB_ENV

      # 5. Configurer les variables d’environnement
      - name: Configure database environment variables
        run: |
          echo "FTP_USERNAME=${{ secrets.FTP_USERNAME }}" >> $GITHUB_ENV 
          echo "FTP_PASSWORD=${{ secrets.FTP_PASSWORD }}" >> $GITHUB_ENV 
          echo "SERVER_URL=${{ secrets.SERVER_URL }}" >> $GITHUB_ENV 
          echo "PROD_DB_HOST=${{ secrets.PROD_DB_HOST }}" >> $GITHUB_ENV 
          echo "PROD_DB_USER=${{ secrets.PROD_DB_USER }}" >> $GITHUB_ENV 
          echo "PROD_DB_PASSWORD=${{ secrets.PROD_DB_PASSWORD }}" >> $GITHUB_ENV 
          echo "PROD_DB_NAME=${{ secrets.PROD_DB_NAME }}" >> $GITHUB_ENV
          echo "PROD_DB_PORT=${{secrets.PROD_DB_PORT}}" >> $GITHUB_ENV

      # 7. Installation dependances du front
      - name: install front dependencies
        run: |
          cd frontv2
          npm install
      # 7. Build du frontend
      - name: Build frontend
        run: |
          cd frontv2
          npm run build

      # 8. Déplacer le frontend compilé dans le backend
      - name: Move frontend to backend
        run: mv frontv2/dist Back/public

      # 9. Déployer le backend
      - name: Deploy backend
        run: |
          cd Back
          node server.js

        #10. Deployer sur le ftp
      - name: FTP Deploy
        # You may pin to the exact commit or the version.
        # uses: SamKirkland/FTP-Deploy-Action@8e83cea8672e3fbcbb9fdafff34debf6ae4c5f65
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          # ftp server
          server: ftp.abhi4136.odns.fr
          # ftp username
          username: 08@01-web.formation-adapeco-sofip.com
          # ftp password
          password: aqFbABLGFz6wVhLe
          # Server port to connect to (read your web hosts docs)
          port: 21
          # protocol to deploy with - ftp, ftps, or ftps-legacy
          protocol: ftp
          # Folder to upload from, must end with trailing slash /
          local-dir: /
          # Path to upload to on the server. Must end with trailing slash /
          server-dir: 08/
          
